/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-01 14:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import beans.Book;

public final class showStock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link href=\"style/showStock.css\" rel=\"stylesheet\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>hello here</h1>\r\n");
      out.write("<table  width=\"80%\">\r\n");
      out.write("<!-- \t\t\t<th>选择</th> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<th>图书标题</th>\r\n");
      out.write("\t\t\t<th>类别</th>\r\n");
      out.write("\t\t\t<th>价格</th>\r\n");
      out.write("\t\t\t<th>库存</th>\r\n");
      out.write("\t\t\t<th>状态</th>\r\n");
      out.write("\t\t\t<th>操作</th>\r\n");

	ArrayList<Book> books=(ArrayList<Book>)request.getAttribute("books");
	for(Book book:books)
	{
		String status;
		if(book.getBook_status().equals("0"))	status = "下架";
		else	status = "上架"; 
	
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<input type='hidden' name='book_id' id='book_id' value=");
      out.print(book.getBook_id());
      out.write(" />\r\n");
      out.write("<!-- \t\t\t\t<td> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t\t\t</td> -->\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<img id=\"thumbNail\" src=");
      out.print(book.getBook_pic() );
      out.write("    />\r\n");
      out.write("\t\t\t\t\t<a href='#'>");
      out.print(book.getBook_title() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(book.getCategory_name() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(book.getBook_price() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print(book.getBook_amount() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span>");
      out.print("已"+status );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<span><a href='editItem?action=edit&book_id=");
      out.print(book.getBook_id());
      out.write("' >编辑</a></span></br>\r\n");
      out.write("\t\t\t\t\t");

						if(status.equals("上架"))
						{
							out.println("<span><a class='pullput' href='editItem?book_id="+ book.getBook_id() +"&action=pull'>下架</a></span>");
						}
						else
							out.println("<span><a class='pullput' href='editItem?book_id="+ book.getBook_id() +"&action=put'>上架</a></span>");
							
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</br><span ><a class=\"delete\" href='editItem?action=delete&book_id=");
      out.print(book.getBook_id());
      out.write("' >删除</a></span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"button\" id=\"addItem\" name=\"addItem\" value=\"添加图书\" />\r\n");
      out.write("<script src=\"script/jquery-1.6.2.min.js\"></script>\r\n");
      out.write("<script src=\"script/showStock.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
